### ISSUE TITLE
Deserialization error in `LibpodContainerInspectResponse::host_config::port_bindings`

### ISSUE THREAD

**Issue by marhkb** [vv9k/podman-api-rs#111]
- Crate version: 0.2.1
- OS: Fedora Linux 35.20220322.1 (Silverblue)
- Output of running `podman version` on the command line:
```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 22:45:07 2021
OS/Arch:      linux/amd64
```

I'm facing deserialization errors for some of my containers. It seems that `port_bindings` can have `null` as values?

Here is the `LibpodContainerInspectResponse` from an affected container (I had to put a `.zip` at the end of the text file. Else, github wouldn't allow me to upload the file):
[test.json.zip](https://github.com/vv9k/podman-api-rs/files/8349976/test.json.zip)

This is the error I'm getting when trying to deserialize this json
```
> Executing task: cargo test --package podman-api --lib -- api::containers::test --nocapture <

    Finished test [unoptimized + debuginfo] target(s) in 0.56s
     Running unittests (target/debug/deps/podman_api-cc7230060d3387cf)

running 1 test
thread 'api::containers::test::test' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected a sequence", line: 222, column: 29)', src/api/containers.rs:1174:91
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1018:23
   4: podman_api::api::containers::test::test
             at ./src/api/containers.rs:1174:9
   5: podman_api::api::containers::test::test::{{closure}}
             at ./src/api/containers.rs:1173:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test api::containers::test::test ... FAILED

failures:

failures:
    api::containers::test::test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.02s

error: test failed, to rerun pass '-p podman-api --lib'
```

**Comment by vv9k** [comment]
I confirmed that there indeed is a problem with serialization of the PortBindings field on the inspect response. I'm still trying to figure out how to handle it cleanly in the java codegen, so far my trials weren't so successful. As a last resort I might just add a manual patch to the build script that fixes this.

**Comment by vv9k** [comment]
I've decided to fix it by patching it in the build script for now. The issue should be resolved for now :)

**Comment by vv9k** [comment]
I'll close this issue and leave #113 as a tracking issue for fixing the codegen of `PortMap` as it is the type of `ContainerJson::host_config::port_bindings` field that this issue concerns.
